version: '3'

services:
  #Image for apache, php, node
  web:
    build:
      context: ./images/php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./:/var/www

  #Image for proxy server
  proxy:
    build:
      context: ./images/proxy
    container_name: proxy
    image: nginx
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-8080}:80
    depends_on:
      - web
    volumes:
      - ./:/var/www
      - ./images/proxy/:/etc/nginx/conf.d/